### ISSUE TITLE
Missing instructions on how to install the core library

### ISSUE THREAD

**Issue by bmispelon** [editorconfig/editorconfig-gedit#10]
The installation sections says:

> First, make sure the core EditorConfig Python library is installed on your machine.

However, it is unclear to me which library we're talking about, or how I should proceed to install it on my machine (should I use an OS package, install globally with pip, or just for my user, ...?).

**Comment by xuhdev** [comment]
I've added a link to the EditorConfig Python Core library in README, which should lead you to the installation instruction of the core library. You can either install it globally or for yourself or the OS package: it is just like other Python libraries.

**Comment by bmispelon** [comment]
Perfect, thanks for responding so quickly! :sparkles:
