### ISSUE TITLE
Download via git currently broken

### ISSUE THREAD

**Issue by webmaster128** [editorconfig/editorconfig-gedit#13]
When I try to `git clone --recursive git://github.com/editorconfig/editorconfig-gedit.git` I get the error

```
Cloning into 'editorconfig-gedit'...
remote: Counting objects: 583, done.
remote: Total 583 (delta 0), reused 0 (delta 0), pack-reused 583
Receiving objects: 100% (583/583), 124.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (291/291), done.
Checking connectivity... done.
fatal: no submodule mapping found in .gitmodules for path 'editorconfig-core-py/tests'
```

The same happen when I do it in two steps as described in the readme.

**Comment by xuhdev** [comment]
`editorconfig-core-py` is a subtree which contains a submodule. This cannot be handled by git properly yet. The README was written before `editorconfig-core-py` became a subtree -- it was a submodule before.
