### ISSUE TITLE
'python' plugin loader problem

### ISSUE THREAD

**Issue by webmaster128** [editorconfig/editorconfig-gedit#14]
After installing the plugin version 0.5.3 (Manual installation) on Ubuntu 16.04 (gedit 3.18.3), I get the error:

> libpeas-WARNING **: The 'python' plugin loader has not been enabled

When changing `Loader=python` to `Loader=python3` in editorconfig.plugin, the error goes away.

No virtualenv is used and the `python` executable is `Python 2.7.12`.

**Comment by xuhdev** [comment]
Maybe your gedit did not enable the python loader, which caused the issue?

**Comment by webmaster128** [comment]
How to enable these loaders?

**Comment by xuhdev** [comment]
Should be fixed in 53d469c8fa91b147417ad0bb4fe9f38925141952

Looks like people are moving onto python3 loader.
