### ISSUE TITLE
Merge conflicts when attempting git subtree pull

### ISSUE THREAD

**Issue by jefferyto** [editorconfig/editorconfig-gedit#21]
I'm trying to update the core library (to the commit I believe is 0.12.2) with:

```
git subtree pull --prefix=editorconfig-core-py editorconfig-core-py 596da5e06ebee05bdbdc6224203c79c4d3c6486a
```

but I get lots of merge conflicts as a result.

I know it's under consideration [whether or not to use `git submodule` instead](https://github.com/editorconfig/editorconfig-gedit/pull/17), but I thought I would try updating the library in the meantime.

I'm not an expert at git so I'm not sure what do to at this point. (It looks like 35c063e9fd078889f1d3dbfb4b6a8a0e6b5f4779 was a manual upgrade without `git subtree`, so I believe it may be the cause?) How can I resolve this in the cleanest way possible?

**Comment by xuhdev** [comment]
@treyhunner Do you remember what happened? If it was a true misoperation, we may need to rebuild the subtree...

**Comment by jefferyto** [comment]
I tried `git revert 35c063e` before `git subtree pull` and it seems to have merged correctly.

**Comment by treyhunner** [comment]
That was likely a mistake on my end.

**Comment by xuhdev** [comment]
Should be fixed now.
