### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by rugk** [editorconfig/editorconfig-gedit#22]
You can [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Comment by xuhdev** [comment]
This is still maintained. Do you have a bug in mind?
